python -m unittest tests/__init__.py
python -m unittest tests/test_fastp.py
python -m unittest tests/test_fastqc.py
python -m unittest tests/test_gffcompare.py
python -m unittest tests/test_hisat2.py
python -m unittest tests/test_samtools.py
python -m unittest tests/test_star.py
python -m unittest tests/test_stringtie.py
python -m unittest tests/test_trinity.py
python -m unittest tests/test_minimap2.py
