
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "create samtools test environment"
          command: |
            source activate base
            conda env create --file conda-envs/test.yml --prune
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

  test_samtools:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - run:
          name: "samtools test"
          command: |
            source activate samtools
            python -m unittest tests/test_samtools.py
#  Test_fastp_bwa_fastqc_minimap2_picard_gatk4:
#    docker:
#      - image: continuumio/miniconda3:4.7.12
#
#    working_directory: ~/repo
#
#    steps:
#      - checkout
#      - run:
#          name: "Pull Submodules"
#          command: |
#            git submodule init
#            git submodule update --remote
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "conda-env.yml" }}
#
#      - run:
#          name: "conda environment build"
#          command: |
#            source activate base
#            conda env update --file conda-env.yml --prune
#
#
#      - save_cache:
#          paths:
#            - /opt/conda
#          key: v1-dependencies-{{ checksum "conda-env.yml" }}
#
#      - run:
#          name: run tests
#          command: |
#            source activate base
#            sh test.sh
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test_samtools:
          requires:
            - build
