
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "create samtools test environment"
          command: |
            source activate base
            conda env create --file conda-envs/samtools.yml -n samtools
      - run:
          name: "create minimap2 test environment"
          command: |
            source activate base
            conda env create --file conda-envs/minimap2.yml -n minimap2
      - save_cache:
          key: v1-conda-environments-{{ checksum "conda-envs/samtools.yml" }}
          paths:
            - /opt/conda/envs/samtools
      - save_cache:
          key: v1-conda-environments-{{ checksum "conda-envs/minimap2.yml" }}
          paths:
            - /opt/conda/envs/minimap2



  test_samtools:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-conda-environments-{{ checksum "conda-envs/samtools.yml" }}
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "samtools test"
          command: |
            source activate samtools
            python -m unittest tests/test_samtools.py

  test_minimap2:
    docker:
      - image: continuumio/miniconda3:4.7.12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-conda-environments-{{ checksum "conda-envs/minimap2.yml" }}
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: "minimap2 test"
          command: |
            source activate minimap2
            python -m unittest tests/test_minimap2.py
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test_samtools:
          requires:
            - build
      - test_minimap2:
          requires:
            - build
