
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.7.12

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "conda-env.yml" }}

      - run:
          name: "conda environment build"
          command: |
            conda create -f conda-env.yml -p ./biocore-test
            conda activate ./biocore-test

      - save_cache:
          paths:
            - ./biocoore-test
          key: v1-dependencies-{{ checksum "conda-env.yml" }}

      - run:
          name: run tests
          command: |
            conda activate ./biocore-test
            sh test.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports